# Generated by Django 3.2.5 on 2021-08-03 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nairobi CBD', 'Nairobi CBD'), ('Eastern Bypass', 'Eastern Bypass'), ('Eastlands', 'Eastlands'), ('Jogoo Road', 'Jogoo Road'), ('Kamiti Road', 'Kamiti Road'), ('Kangudo Road', 'Kangudo Road'), ('Langata Road', 'Langata Road'), ('Manyanja Road', 'Manyanja Road'), ('Mbagathi Way', 'Mbagathi Way'), ('Ngong Road', 'Ngong Road'), ('Mombasa Road', 'Mombasa Road'), ('Naivasha Road', 'Naivasha Road'), ('Outering Road', 'Outering Road'), ('Thika Road', 'Thika Road'), ('Waiyaki Way', 'Waiyaki Way'), ('Athi River', 'Athi River'), ('Allsops', 'Allsops'), ('Buruburu', 'Buruburu'), ('Donholm', 'Donholm'), ('Embakasi', 'Embakasi'), ('Eastleigh', 'Eastleigh'), ('Githurai', 'Githurai'), ('Homeland', 'Homeland'), ('Hurlingham', 'Hurlingham'), ('Imara Daima', 'Imara Daima'), ('Kasarani', 'Kasarani'), ('Juja', 'Juja'), ('Karen', 'Karen'), ('Kabete', 'Kabete'), ('Kahawa Wendani', 'Kahawa Wendani'), ('Kahawa West', 'Kahawa West'), ('Kahawa Sukari', 'Kahawa Sukari'), ('Kayole', 'Kayole'), ('Kawangware', 'Kawangware'), ('Kileleshwa', 'Kileleshwa'), ('Kilimani', 'Kilimani'), ('Kiambu', 'Kiambu'), ('Kikuyu Town', 'Kikuyu Town'), ('Kitengela', 'Kitengela'), ('Langata', 'Langata'), ('Madaraka', 'Madaraka'), ('Milimani', 'Milimani'), ('Mlolongo', 'Mlolongo'), ('Muthaiga', 'Muthaiga'), ('Mwiki', 'Mwiki'), ('Nairobi West', 'Nairobi West'), ('Eastleigh', 'Eastleigh'), ('Lavington', 'Lavington'), ('Ngara', 'Ngara'), ('Pangani', 'Pangani'), ('Parklands', 'Parklands'), ('Ruaka', 'Ruaka'), ('Ruiru', 'Ruiru'), ('Rongai', 'Rongai'), ('Roysambu', 'Roysambu'), ('Ruai', 'Ruai'), ('Runda', 'Runda'), ('South C', 'South C'), ('South B', 'South B'), ('Syokimau', 'Syokimau'), ('Thome', 'Thome'), ('Umoja', 'Umoja'), ('Upper Hill', 'Upper Hill'), ('Utawala', 'Utawala'), ('Westlands', 'Westlands'), ('Yaya', 'Yaya'), ('Bungoma', 'Bungoma'), ('Diani', 'Diani'), ('Eldoret', 'Eldoret'), ('Emali', 'Emali'), ('Embu', 'Embu'), ('Isiolo', 'Isiolo'), ('Kericho', 'Kericho'), ('Kakamega', 'Kakamega'), ('Karatina', 'Karatina'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Kisii', 'Kisii'), ('Limuru', 'Limuru'), ('Lodwar', 'Lodwar'), ('Loitoktok', 'Loitoktok'), ('Machakos', 'Machakos'), ('Mai Mahiu', 'Mai Mahiu'), ('Malindi', 'Malindi'), ('Meru', 'Meru'), ('Naivasha', 'Naivasha'), ('Mombasa', 'Mombasa'), ('Nakuru', 'Nakuru'), ('Nanyuki', 'Nanyuki'), ('Nyahururu', 'Nyahururu'), ('Nyeri', 'Nyeri'), ('Thika', 'Thika'), ('Voi', 'Voi')], max_length=40)),
                ('review', models.TextField(default='Beautiful escorts babes', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VIP', 'VIP'), ('PREMIUM', 'PREMIUM'), ('NEW', 'NEW')], default='New', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(default='22', max_length=2)),
                ('about_me', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('ethnicity', models.CharField(max_length=20)),
                ('orientation', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=15)),
                ('skin_color', models.CharField(max_length=40)),
                ('hair_color', models.CharField(max_length=40)),
                ('services', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anescort.location')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anescort.membership')),
            ],
            options={
                'ordering': ['-membership'],
            },
        ),
    ]
