# Generated by Django 3.2.5 on 2021-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anescort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='review',
        ),
        migrations.AlterField(
            model_name='escort',
            name='area',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='escort',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
