# Generated by Django 3.2.5 on 2021-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anescort', '0004_alter_escort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='escort',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='escort',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
